### ISSUE TITLE
Create contraptions not gathering crops while addon active in NeoForge 1.20.1

### ISSUE THREAD

**Issue by wault404** [ValkyrienSkies/Create-Interactive-Issues#87]
I do understand the official BETA is only for Forge. 
Just wanted to let you know.

**Comment by materusPL** [comment]
I've noticed same problem, contraptions inventory seems to not collect anything while in non interactive mode, if I add "interact me" block it collect items as expected. 
But due to https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/55 I'd rather not make many interactive contraptions.

**Comment by blockninja124** [comment]
Fixed in dev

**Comment by blockninja124** [comment]
Duplicate of https://github.com/ValkyrienSkies/Create-Interactive-Issues/issues/91, and fixed in dev so closing
